[package]
name = "pades_rsa"
type = "bin"
authors = [""]
compiler_version = ">=0.35.0"

[dependencies]
noir_rsa = { git = "https://github.com/zkpassport/noir_rsa", tag = "v0.9.2" }
bignum = { git = "https://github.com/noir-lang/noir-bignum", tag = "v0.8.2" }
