[package]
name = "pades_rsa"
type = "bin"
authors = [""]
compiler_version = ">=0.35.0"

[dependencies]
pades_common = { path = "../pades_common" }
noir_rsa = { git = "https://github.com/d3mage/noir_rsa.git", tag = "main" }
bignum = { git = "https://github.com/noir-lang/noir-bignum", tag = "v0.8.3" }
